export const enCatalog = {
  'areas.circularReference':
    'Cannot set the parent area because it would create a circular reference.',
  'areas.deleted': 'Area deleted successfully.',
  'areas.locationNotFound': 'Location not found.',
  'areas.notFound': 'Area not found.',
  'areas.parentLocationMismatch':
    'The parent area must belong to the same location.',
  'areas.parentNotFound': 'Parent area not found.',
  'areas.repositoryFailed': 'Area operation failed.',
  'areas.selfParent': 'An area cannot be its own parent.',
  'audit.writeFailed': 'Audit log write failed.',
  'auditLogs.notFound': 'Audit log not found.',
  'auditLogs.repositoryFailed': 'Audit log operation failed.',
  'auth.permissionDenied': 'Insufficient permissions.',
  'auth.unauthorized': 'Unauthorized.',
  'e2e.seedDisabled': 'E2E seeding is disabled.',
  'e2e.seedFailed': 'E2E seed failed.',
  'email.sendFailed': 'Email delivery failed.',
  'email.welcomeRequestFailed': 'Failed to request the welcome email.',
  'tenant.membershipRejected':
    'The active tenant is not available for this user.',
  'tenant.notResolved': 'No active tenant could be resolved for this request.',
  'tenant.hostNotFound': 'Tenant host not found.',
  'tenantFeatures.repositoryFailed': 'Tenant feature operation failed.',
  'branding.repositoryFailed': 'Branding operation failed.',
  'branding.sessionUserUnavailable': 'Session user is not available.',
  'categories.circularReference':
    'Cannot set the parent category because it would create a circular reference.',
  'categories.deleted': 'Category deleted successfully.',
  'categories.nameAlreadyExists': 'A category with this name already exists.',
  'categories.notFound': 'Category not found.',
  'categories.parentNotFound': 'Parent category not found.',
  'categories.repositoryFailed': 'Category operation failed.',
  'categories.selfParent': 'A category cannot be its own parent.',
  'clients.deleted': 'Client deleted successfully.',
  'clients.emailAlreadyExists':
    'A client with this email address already exists.',
  'clients.notFound': 'Client not found.',
  'clients.repositoryFailed': 'Client operation failed.',
  'db.query': 'Database query executed.',
  'drizzle.initializationFailed':
    'Failed to initialize the database connection.',
  'drizzle.migrationsFailed': 'Failed to run Better Auth migrations.',
  'errors.internalServerError': 'Internal Server Error.',
  'features.notEnabled': 'This feature is not enabled for the active tenant.',
  'features.repositoryFailed': 'Feature entitlement operation failed.',
  'features.tenantNotFound': 'Tenant not found.',
  'fulfillment.infrastructureFailed': 'Fulfillment operation failed.',
  'fulfillment.insufficientInventory':
    'Insufficient inventory to fulfill the pick.',
  'fulfillment.notPickable': 'The order must already be confirmed or picking.',
  'fulfillment.onlyDraftCanConfirm': 'Only draft orders can be confirmed.',
  'fulfillment.orderItemNotFound': 'Order item not found.',
  'fulfillment.orderNotFound': 'Order not found.',
  'fulfillment.overPick':
    'The picked quantity would exceed the ordered amount.',
  'fulfillment.packNotImplemented':
    'Packing is not implemented yet in the fulfillment workflow.',
  'fulfillment.shipNotImplemented':
    'Shipping is not implemented yet in the fulfillment workflow.',
  'health.betterAuthConfigured': 'Better Auth is properly configured.',
  'health.betterAuthSecretMissing': 'BETTER_AUTH_SECRET is not configured.',
  'health.databaseUnreachable': 'Database is unreachable.',
  'http.parseError': 'Invalid request payload: {details}',
  'http.request': 'HTTP request completed.',
  'http.requestBodyTooLarge': 'Request body exceeds the 10 MB limit.',
  'http.requestError': 'Invalid request: {details}',
  'http.routeNotFound': 'Cannot {method} {path}.',
  'http.serverError': 'HTTP server error.',
  'http.unexpectedError': 'Unexpected error: {details}',
  'inventory.alreadyExists':
    'Inventory already exists for this product and location.',
  'inventory.areaLocationMismatch':
    'The selected area must belong to the selected location.',
  'inventory.areaNotFound': 'Area not found.',
  'inventory.deleted': 'Inventory item deleted successfully.',
  'inventory.infrastructureFailed': 'Inventory operation failed.',
  'inventory.locationNotFound': 'Location not found.',
  'inventory.notFound': 'Inventory item not found.',
  'inventory.productNotFound': 'Product not found.',
  'inventory.quantityAdjustmentNegative':
    'The inventory adjustment would result in a negative quantity.',
  'locations.deleted': 'Location deleted successfully.',
  'locations.notFound': 'Location not found.',
  'locations.repositoryFailed': 'Location operation failed.',
  'notifications.preferencesUpdated': 'Notification preferences updated.',
  'notifications.repositoryFailed': 'Notification operation failed.',
  'notifications.sendFailed': 'Notification delivery failed.',
  'orders.clientNotFound': 'Client not found.',
  'orders.deleteOnlyDraft': 'Only draft orders can be deleted.',
  'orders.deleted': 'Order deleted successfully.',
  'orders.infrastructureFailed': 'Order operation failed.',
  'orders.invalidStatusTransition': 'Cannot transition from {from} to {to}.',
  'orders.notFound': 'Order not found.',
  'orders.productNotFound': 'Product not found.',
  'photos.deleted': 'Photo deleted successfully.',
  'photos.deleteFailed': 'Failed to delete the photo object.',
  'photos.existenceCheckFailed': 'Failed to check whether the photo exists.',
  'photos.fileNotFound': 'Photo object not found in storage.',
  'photos.invalidMimeType': 'Invalid file type. Allowed types: {allowedTypes}.',
  'photos.notFound': 'Photo not found.',
  'photos.readFailed': 'Failed to read the photo object.',
  'photos.readUploadFailed': 'Failed to read the uploaded file.',
  'photos.repositoryFailed': 'Photo operation failed.',
  'photos.statUploadFailed': 'Failed to read uploaded file metadata.',
  'photos.tooLarge':
    'File is too large. Maximum allowed size is {maxSize} bytes.',
  'photos.writeFailed': 'Failed to write the photo object.',
  'platform.hostRequired': 'Platform route not found for this host.',
  'products.categoryNotFound': 'Category not found.',
  'products.createdProductLoadFailed': 'Failed to load the created product.',
  'products.deleted': 'Product deleted successfully.',
  'products.deletedPermanent': 'Product permanently deleted.',
  'products.importAreaScopedInventoryConflict':
    'Cannot import location-level inventory while area-scoped inventory exists for this product and location.',
  'products.importAreaLocationRequired':
    'A default location is required to import area-scoped inventory.',
  'products.importCsvParseFailed': 'Could not parse the uploaded CSV file.',
  'products.importPlanParseFailed':
    'Could not parse the uploaded product import plan.',
  'products.importReadUploadFailed':
    'Failed to read the uploaded product import file.',
  'products.importUnsupportedFormat': 'Unsupported product import CSV headers.',
  'products.infrastructureFailed': 'Product operation failed.',
  'products.notDeleted': 'Product is not deleted.',
  'products.notFound': 'Product not found.',
  'products.priceBelowCost':
    'Standard price must be greater than or equal to standard cost.',
  'products.repositoryFailed': 'Product operation failed.',
  'products.skuAlreadyExists': 'A product with this SKU already exists.',
  'roles.infrastructureFailed': 'Role operation failed.',
  'roles.loadPermissionsFailed': 'Failed to load user permissions.',
  'roles.nameAlreadyExists': 'A role with this name already exists.',
  'roles.notFound': 'Role not found.',
  'roles.repositoryFailed': 'Role operation failed.',
  'roles.systemDeletionForbidden': 'System roles cannot be deleted.',
  'session.resolveFailed': 'Failed to resolve the user session.',
  'superadmin.forbidden': 'Superadmin access is required.',
  'superadmin.invalidTenantSlug': 'Tenant slug is invalid.',
  'superadmin.infrastructureFailed': 'Superadmin authorization failed.',
  'superadmin.repositoryFailed': 'Superadmin operation failed.',
  'superadmin.reservedTenantSlug': 'Tenant slug is reserved.',
  'superadmin.tenantHostnameAlreadyExists':
    'A tenant with this hostname already exists.',
  'superadmin.tenantImportInvalid': 'Tenant import failed: {details}',
  'superadmin.tenantNotFound': 'Tenant not found.',
  'superadmin.tenantSlugAlreadyExists':
    'A tenant with this slug already exists.',
  'stockMovements.destinationLocationNotFound':
    'Destination location not found.',
  'stockMovements.infrastructureFailed': 'Stock movement operation failed.',
  'stockMovements.locationNotFound': 'Location not found.',
  'stockMovements.notFound': 'Stock movement not found.',
  'stockMovements.orderNotFound': 'Order not found.',
  'stockMovements.productNotFound': 'Product not found.',
  'stockMovements.repositoryFailed': 'Stock movement operation failed.',
  'stockMovements.sourceLocationNotFound': 'Source location not found.',
  'suppliers.deleted': 'Supplier deleted successfully.',
  'suppliers.notFound': 'Supplier not found.',
  'suppliers.repositoryFailed': 'Supplier operation failed.',
  'tasks.executionDefect':
    'Background task {taskId} ({taskType}) encountered an unexpected defect on worker {workerId}: {error}',
  'tasks.leaseLost':
    'Worker {workerId} lost the lease for background task {taskId} ({taskType}).',
  'tasks.notFound': 'Background task not found.',
  'tasks.recovered':
    'Worker {workerId} recovered {taskCount} background task(s) with expired leases.',
  'tasks.recoveryFailed':
    'Background task recovery failed on worker {workerId}: {error}',
  'tasks.repositoryFailed': 'Background task operation failed.',
  'tasks.settled':
    'Background task {taskId} ({taskType}) settled as {status} on worker {workerId}.',
  'tasks.settlementFailed':
    'Background task {taskId} ({taskType}) could not be settled by worker {workerId}: {error}',
  'tasks.terminalConflict': 'The background task has already finished.',
  'tasks.workerFailed': 'Background task worker {workerId} failed: {error}',
  'tasks.workerStarted': 'Background task worker {workerId} started.',
  'users.infrastructureFailed': 'User operation failed.',
  'users.notFound': 'User not found.',
  'users.repositoryFailed': 'User operation failed.',
} as const;

export type MessageKey = keyof typeof enCatalog;
