export interface LogProperties {
  readonly action: string;
  readonly actualSchemaVersion: string;
  readonly allowedTypes: string;
  readonly cause: unknown;
  readonly details: string;
  readonly durationMs: number;
  readonly entityId: string;
  readonly entityType: string;
  readonly error: unknown;
  readonly expectedSchemaVersion: string;
  readonly from: string;
  readonly maxSize: number;
  readonly method: string;
  readonly path: string;
  readonly processedRows: number;
  readonly requestId: string;
  readonly status: string;
  readonly statusCode: number;
  readonly taskCount: number;
  readonly taskId: string;
  readonly taskType: string;
  readonly template: string;
  readonly tenantId: string;
  readonly to: string;
  readonly totalRows: number;
  readonly userAgent: string;
  readonly workerId: string;
}
