import { sql, type SQL } from 'drizzle-orm';
import { seedSuperAdmin } from '../../../scripts/seed-superadmin';
import type { DrizzleDb } from './drizzle';

const DATA_MIGRATIONS_TABLE_NAME = 'stocket_data_migrations';
const SEED_PLATFORM_SUPERADMIN_MIGRATION = '0000_seed_platform_superadmin';

type SqlExecutor = {
  readonly execute: (query: SQL) => Promise<unknown>;
};

type SqlResult = {
  readonly rows?: ReadonlyArray<Record<string, unknown>>;
};

export interface FreshDatabaseDataMigrationOptions {
  readonly freshSchemaCreated: boolean;
}

async function executeSql(
  executor: SqlExecutor,
  query: SQL | string,
): Promise<ReadonlyArray<Record<string, unknown>>> {
  const result = (await executor.execute(
    typeof query === 'string' ? sql.raw(query) : query,
  )) as SqlResult;

  return Array.isArray(result.rows) ? result.rows : [];
}

async function dataMigrationsTableExists(db: DrizzleDb): Promise<boolean> {
  const rows = await executeSql(
    db,
    sql.raw(
      `SELECT to_regclass('public.${DATA_MIGRATIONS_TABLE_NAME}') IS NOT NULL AS table_exists`,
    ),
  );

  return rows[0]?.table_exists === true;
}

async function ensureDataMigrationsTable(db: DrizzleDb): Promise<void> {
  await executeSql(
    db,
    `CREATE TABLE IF NOT EXISTS ${DATA_MIGRATIONS_TABLE_NAME} (
      name text PRIMARY KEY,
      applied_at timestamptz NOT NULL DEFAULT now()
    )`,
  );
}

async function hasDataMigrationApplied(
  db: DrizzleDb,
  migrationName: string,
): Promise<boolean> {
  const rows = await executeSql(
    db,
    sql`
      SELECT name
      FROM stocket_data_migrations
      WHERE name = ${migrationName}
      LIMIT 1
    `,
  );

  return rows.length > 0;
}

async function markDataMigrationApplied(
  db: DrizzleDb,
  migrationName: string,
): Promise<void> {
  await executeSql(
    db,
    sql`
      INSERT INTO stocket_data_migrations (name)
      VALUES (${migrationName})
      ON CONFLICT (name) DO NOTHING
    `,
  );
}

export async function prepareFreshDatabaseDataMigrations(
  db: DrizzleDb,
  options: FreshDatabaseDataMigrationOptions,
): Promise<void> {
  if (!options.freshSchemaCreated) {
    return;
  }

  await ensureDataMigrationsTable(db);
}

export async function runFreshDatabaseDataMigrations(
  db: DrizzleDb,
  options: FreshDatabaseDataMigrationOptions,
): Promise<void> {
  const hasPendingDataMigrations = await dataMigrationsTableExists(db);
  if (!options.freshSchemaCreated && !hasPendingDataMigrations) {
    return;
  }

  await ensureDataMigrationsTable(db);
  if (await hasDataMigrationApplied(db, SEED_PLATFORM_SUPERADMIN_MIGRATION)) {
    return;
  }

  // This stays in TypeScript rather than SQL because Better Auth password
  // hashes are generated by its JS crypto helper.
  await seedSuperAdmin();
  await markDataMigrationApplied(db, SEED_PLATFORM_SUPERADMIN_MIGRATION);
}
