import { sql, type SQL } from 'drizzle-orm';
import {
  readSuperAdminSeedConfig,
  seedSuperAdmin,
} from '../../../scripts/seed-superadmin';
import type { DrizzleDb } from './drizzle';

const DATA_MIGRATIONS_TABLE_NAME = 'stocket_data_migrations';
const SEED_PLATFORM_SUPERADMIN_MIGRATION = '0000_seed_platform_superadmin';
const RECONCILE_PLATFORM_SUPERADMIN_PASSWORD_MIGRATION =
  '0001_reconcile_platform_superadmin_password';

type SqlExecutor = {
  readonly execute: (query: SQL) => Promise<unknown>;
};

type SqlResult = {
  readonly rows?: ReadonlyArray<Record<string, unknown>>;
};

export interface FreshDatabaseDataMigrationOptions {
  readonly freshSchemaCreated: boolean;
}

async function executeSql(
  executor: SqlExecutor,
  query: SQL | string,
): Promise<ReadonlyArray<Record<string, unknown>>> {
  const result = (await executor.execute(
    typeof query === 'string' ? sql.raw(query) : query,
  )) as SqlResult;

  return Array.isArray(result.rows) ? result.rows : [];
}

async function ensureDataMigrationsTable(db: DrizzleDb): Promise<void> {
  await executeSql(
    db,
    `CREATE TABLE IF NOT EXISTS ${DATA_MIGRATIONS_TABLE_NAME} (
      name text PRIMARY KEY,
      applied_at timestamptz NOT NULL DEFAULT now()
    )`,
  );
}

async function hasDataMigrationApplied(
  db: DrizzleDb,
  migrationName: string,
): Promise<boolean> {
  const rows = await executeSql(
    db,
    sql`
      SELECT name
      FROM stocket_data_migrations
      WHERE name = ${migrationName}
      LIMIT 1
    `,
  );

  return rows.length > 0;
}

async function markDataMigrationApplied(
  db: DrizzleDb,
  migrationName: string,
): Promise<void> {
  await executeSql(
    db,
    sql`
      INSERT INTO stocket_data_migrations (name)
      VALUES (${migrationName})
      ON CONFLICT (name) DO NOTHING
    `,
  );
}

async function seedSuperAdminWithPasswordRotation(): Promise<void> {
  await seedSuperAdmin({
    ...(await readSuperAdminSeedConfig()),
    rotatePassword: true,
  });
}

const dataMigrations: ReadonlyArray<{
  readonly name: string;
  readonly run: () => Promise<void>;
}> = [
  {
    name: SEED_PLATFORM_SUPERADMIN_MIGRATION,
    run: seedSuperAdmin,
  },
  {
    name: RECONCILE_PLATFORM_SUPERADMIN_PASSWORD_MIGRATION,
    run: seedSuperAdminWithPasswordRotation,
  },
];

export async function prepareFreshDatabaseDataMigrations(
  db: DrizzleDb,
  options: FreshDatabaseDataMigrationOptions,
): Promise<void> {
  if (!options.freshSchemaCreated) {
    return;
  }

  await ensureDataMigrationsTable(db);
}

export async function runFreshDatabaseDataMigrations(
  db: DrizzleDb,
  _options: FreshDatabaseDataMigrationOptions,
): Promise<void> {
  await ensureDataMigrationsTable(db);

  for (const migration of dataMigrations) {
    if (await hasDataMigrationApplied(db, migration.name)) {
      continue;
    }

    // These stay in TypeScript rather than SQL because Better Auth password
    // hashes are generated by its JS crypto helper.
    await migration.run();
    await markDataMigrationApplied(db, migration.name);
  }
}
